### ISSUE TITLE
Segfault when launching on Wayland

### ISSUE THREAD

**Issue by etna** [rodlie/qtfm#134]
when passing QT_QPA_PLATFORM=wayland-egl to the binary, QtFM segfaults and dmesg shows the following log:

`[12401.843276] qtfm[25312]: segfault at 0 ip 00007f07623b2b30 sp 00007ffe24dd7450 error 4 in libQt5Core.so.5.4.2[7f0762107000+4ae000]
`

Some help please?

QtFM is v6.1.8 and was built against:
- Qt 5.4.2 (provided by Ubuntu 15.10)
- Harfbuzz 1.5.1 (self-built)

I have built other Qt applications (e.g.: xpdf, keepassxc, nomacs) against this version of Qt and they have no problems launching under Wayland.

**Comment by rodlie** [comment]
I don't use (or have access to) wayland, so you will need to build qtfm in debug mode (CONFIG+=debug) and run it through gdb.

**Comment by rodlie** [comment]
Did a install of Ubuntu 17.10 in Virtualbox and ran 6.1.8 with QT_QPA_PLATFORM=wayland-egl. No segfault.

**Comment by rodlie** [comment]
Btw, qtfm was unusable with wayland-egl on Ubuntu 17.10, this is a Qt (on Wayland) issue.

Normal:
![VirtualBox_Ubuntu 17](https://user-images.githubusercontent.com/34516798/56514457-950f7100-6535-11e9-8c05-b66d9e391dc6.png)

Wayland-egl:
![VirtualBox_Ubuntu 172](https://user-images.githubusercontent.com/34516798/56514468-9e98d900-6535-11e9-9861-d34bcc6c0333.png)

**Comment by etna** [comment]
Thanks for waiting; just finished rebuilding in debug mode and still getting segfaults. 

Trying to run qtfm with QT_QPA_PLATFORM=wayland-egl without gdb:
```
etna@ubutrial:~$ LD_LIBRARY_PATH=/home/etna/Applications/everything/qtfm/build2/lib:/home/etna/Applications/opt/webkitgtk223/lib:/home/etna/Applications/opt/webp/lib:/home/etna/Applications/opt/harfbuzz151/lib:/home/etna/Applications/lib:$LD_LIBRARY_PATH P
ATH=/home/etna/Applications/everything/qtfm/build2/bin:/home/etna/Applications/opt/webkitgtk223/bin:/home/etna/Applications/opt/webkitgtk223/libexec:/home/etna/Applications/opt/webp/bin:/home/etna/Applications/opt/harfbuzz151/bin:/home/etna/Applications/bi
n:/home/etna/Downloads/CMAKE/bin:$PATH QT_QPA_PLATFORM=wayland-egl QT_WAYLAND_FORCE_DPI=96 qtfm
Debug: Using Wayland-EGL ((null):0, (null))
Debug: using icon theme search path ("/home/etna/.local/share/icons", "/usr/share/icons", ":/icons", "/home/etna/Applications/everything/qtfm/build2/bin/../share/icons") (/home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:62, MainWindow::MainWin
dow())
Debug: checking for icon theme in settings "/home/etna/.config/qtfm6/qtfm6.conf" (/home/etna/Applications/everything/qtfm/libfm/common.cpp:404, static void Common::setupIconTheme(QString))
Debug: setting icon theme "Adwaita" (/home/etna/Applications/everything/qtfm/libfm/common.cpp:448, static void Common::setupIconTheme(QString))
Debug: treeSelectionChanged (/home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:630, void MainWindow::treeSelectionChanged(QModelIndex, QModelIndex))
Debug: addWatcher "/home/etna" (/home/etna/Applications/everything/qtfm/libfm/mymodel.cpp:355, void myModel::addWatcher(myModelItem*))
Debug: trigger dirloaded on tree selection changed (/home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:687, void MainWindow::treeSelectionChanged(QModelIndex, QModelIndex))
Debug: restore window state (/home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:426, void MainWindow::loadSettings(bool, bool, bool, bool))
Debug: dirLoaded triggered, thumbs? true (/home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:700, void MainWindow::dirLoaded(bool))
Debug: updateGrid (/home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:1787, void MainWindow::updateGrid())
Segmentation fault (core dumped)
etna@ubutrial:~$
```

**Comment by etna** [comment]
Trying with gdb:
```
etna@ubutrial:~$ LD_LIBRARY_PATH=/home/etna/Applications/everything/qtfm/build2/lib:/home/etna/Applications/opt/webkitgtk223/lib:/home/etna/Applications/opt/webp/lib:/home/etna/Applications/opt/harfbuzz151/lib:/home/etna/Applications/lib:$LD_LIBRARY_PATH P
ATH=/home/etna/Applications/everything/qtfm/build2/bin:/home/etna/Applications/opt/webkitgtk223/bin:/home/etna/Applications/opt/webkitgtk223/libexec:/home/etna/Applications/opt/webp/bin:/home/etna/Applications/opt/harfbuzz151/bin:/home/etna/Applications/bi
n:/home/etna/Downloads/CMAKE/bin:$PATH QT_QPA_PLATFORM=wayland-egl QT_WAYLAND_FORCE_DPI=96 gdb qtfm
GNU gdb (Ubuntu 7.10-1ubuntu2) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from qtfm...done.
(gdb) run
Starting program: /home/etna/Applications/everything/qtfm/build2/bin/qtfm 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffea412700 (LWP 20198)]
Debug: Using Wayland-EGL ((null):0, (null))
[New Thread 0x7fffe164a700 (LWP 20201)]
Debug: using icon theme search path ("/home/etna/.local/share/icons", "/usr/share/icons", ":/icons", "/home/etna/Applications/everything/qtfm/build2/bin/../share/icons") (/home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:62, MainWindow::MainWin
dow())
Debug: checking for icon theme in settings "/home/etna/.config/qtfm6/qtfm6.conf" (/home/etna/Applications/everything/qtfm/libfm/common.cpp:404, static void Common::setupIconTheme(QString))
Debug: setting icon theme "Adwaita" (/home/etna/Applications/everything/qtfm/libfm/common.cpp:448, static void Common::setupIconTheme(QString))
Debug: treeSelectionChanged (/home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:630, void MainWindow::treeSelectionChanged(QModelIndex, QModelIndex))
Debug: addWatcher "/home/etna" (/home/etna/Applications/everything/qtfm/libfm/mymodel.cpp:355, void myModel::addWatcher(myModelItem*))
Debug: trigger dirloaded on tree selection changed (/home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:687, void MainWindow::treeSelectionChanged(QModelIndex, QModelIndex))
Debug: restore window state (/home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:426, void MainWindow::loadSettings(bool, bool, bool, bool))
Debug: dirLoaded triggered, thumbs? true (/home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:700, void MainWindow::dirLoaded(bool))
Debug: updateGrid (/home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:1787, void MainWindow::updateGrid())

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6a99b30 in QMimeData::hasUrls() const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
(gdb) 
```

**Comment by rodlie** [comment]
Hi, I will need a backtrace from gdb to know what fails (run ``bt`` after segfault). But I think I know what's wrong, I guess the clipboard don't work as it should in wayland and the mime data is NULL.

**Comment by etna** [comment]
Here you go, gdb with backtrace:

```
(gdb) run
Starting program: /home/etna/Applications/everything/qtfm/build2/bin/qtfm 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffea412700 (LWP 19098)]
Debug: Using Wayland-EGL ((null):0, (null))
[New Thread 0x7fffe164a700 (LWP 19099)]
Debug: using icon theme search path ("/home/etna/.local/share/icons", "/usr/share/icons", ":/icons", "/home/etna/Applications/everything/qtfm/build2/bin/../share/icons") (/home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:62, MainWindow::MainWindow(
))
Debug: checking for icon theme in settings "/home/etna/.config/qtfm6/qtfm6.conf" (/home/etna/Applications/everything/qtfm/libfm/common.cpp:404, static void Common::setupIconTheme(QString))
Debug: setting icon theme "Adwaita" (/home/etna/Applications/everything/qtfm/libfm/common.cpp:448, static void Common::setupIconTheme(QString))
Debug: treeSelectionChanged (/home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:630, void MainWindow::treeSelectionChanged(QModelIndex, QModelIndex))
Debug: addWatcher "/home/etna" (/home/etna/Applications/everything/qtfm/libfm/mymodel.cpp:355, void myModel::addWatcher(myModelItem*))
Debug: trigger dirloaded on tree selection changed (/home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:687, void MainWindow::treeSelectionChanged(QModelIndex, QModelIndex))
Debug: restore window state (/home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:426, void MainWindow::loadSettings(bool, bool, bool, bool))
Debug: dirLoaded triggered, thumbs? true (/home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:700, void MainWindow::dirLoaded(bool))
Debug: updateGrid (/home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:1787, void MainWindow::updateGrid())

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6a99b30 in QMimeData::hasUrls() const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
(gdb) bt
#0  0x00007ffff6a99b30 in QMimeData::hasUrls() const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x00000000004285f6 in MainWindow::clipboardChanged (this=0x7fffffffde60) at /home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:947
#2  0x0000000000421531 in MainWindow::lateStart (this=0x7fffffffde60) at /home/etna/Applications/everything/qtfm/fm/src/mainwindow.cpp:301
#3  0x0000000000467012 in MainWindow::qt_static_metacall (_o=0x7fffffffde60, _c=QMetaObject::InvokeMetaMethod, _id=5, _a=0x8c0280) at ../bin/.moc_fm/moc_mainwindow.cpp:428
#4  0x00007ffff6aa1651 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff737fedb in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff749139b in QMainWindow::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff733db8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff7343230 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff6a6ff1b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff6a72057 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff6ac6e73 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff4825ff7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff4826250 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff48262fc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff6ac727f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff6a6d75a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff6a752cc in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x000000000041e708 in main (argc=1, argv=0x7fffffffe2c8) at /home/etna/Applications/everything/qtfm/fm/src/main.cpp:112
(gdb) quit
A debugging session is active.

        Inferior 1 [process 19094] will be killed.

Quit anyway? (y or n) y
etna@ubutrial:~$ 
```

**Comment by rodlie** [comment]
Test the 6.1 branch or apply this patch https://github.com/rodlie/qtfm/commit/6166cbe85c6eae40063ea9377f229c66861dfc00.diff

```
cd <to_qtfm_source>
wget https://github.com/rodlie/qtfm/commit/6166cbe85c6eae40063ea9377f229c66861dfc00.diff
patch -p1< 6166cbe85c6eae40063ea9377f229c66861dfc00.diff
```
rebuild and run.

**Comment by etna** [comment]
Wayland launch success! Thank you very much for the patch. =)
![wayland-screenshot](https://user-images.githubusercontent.com/1294969/56651537-d598f700-66bb-11e9-8f2f-9a38ce7ebaed.png)

**Comment by rodlie** [comment]
Great, thanks for the bug report and info to fix it :)
